<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all()->keyBy('slug');

        $products = [
            // Living Room
            [
                'category_slug' => 'living-room-furniture',
                'name' => 'Modern Luxury Sofa',
                'sku' => 'FS-SOFA-001',
                'short_description' => 'Premium 3-seater luxury sofa with soft fabric upholstery and solid wood legs.',
                'description' => 'Experience ultimate comfort with our Modern Luxury Sofa. Crafted with premium fabric upholstery, high-density foam cushions, and sturdy solid wood legs. Perfect for contemporary living rooms.',
                'price' => 45000,
                'sale_price' => 38000,
                'stock' => 15,
                'material' => 'Premium Fabric, Solid Wood',
                'dimensions' => '220cm x 90cm x 85cm',
                'weight' => '45kg',
                'colors' => ['Walnut Brown', 'Charcoal Grey', 'Beige'],
                'tags' => ['sofa', 'living room', 'luxury', 'fabric'],
                'is_featured' => true,
                'is_best_seller' => true,
                'avg_rating' => 4.8,
                'review_count' => 124,
                'views' => 1250,
                'specifications' => [
                    'Frame Material' => 'Solid Wood',
                    'Upholstery' => 'Premium Woven Fabric',
                    'Cushion Density' => 'High Density Foam',
                    'Legs' => 'Solid Walnut Wood',
                    'Seating Capacity' => '3 Person',
                ],
            ],
            [
                'category_slug' => 'living-room-furniture',
                'name' => 'Wooden Coffee Table',
                'sku' => 'FS-CT-001',
                'short_description' => 'Elegant solid wood coffee table with a natural finish.',
                'description' => 'A beautifully crafted solid wood coffee table that brings warmth and elegance to your living room. Features a lower shelf for additional storage.',
                'price' => 18000,
                'sale_price' => 14500,
                'stock' => 20,
                'material' => 'Solid Sheesham Wood',
                'dimensions' => '120cm x 60cm x 45cm',
                'weight' => '22kg',
                'colors' => ['Natural Wood', 'Dark Walnut', 'Honey Oak'],
                'tags' => ['coffee table', 'wood', 'living room'],
                'is_featured' => true,
                'is_new_arrival' => true,
                'avg_rating' => 4.6,
                'review_count' => 87,
                'views' => 890,
                'specifications' => [
                    'Material' => 'Solid Sheesham Wood',
                    'Finish' => 'Natural Lacquer',
                    'Weight Capacity' => '50kg',
                    'Assembly' => 'Required',
                ],
            ],
            [
                'category_slug' => 'living-room-furniture',
                'name' => 'Minimalist TV Unit',
                'sku' => 'FS-TV-001',
                'short_description' => 'Sleek floating TV unit with cable management.',
                'description' => 'Modern minimalist TV unit with ample storage for media equipment. Features clean lines, hidden cable management, and a premium finish.',
                'price' => 22000,
                'sale_price' => null,
                'stock' => 12,
                'material' => 'MDF, Solid Wood',
                'dimensions' => '180cm x 40cm x 50cm',
                'weight' => '28kg',
                'colors' => ['White Gloss', 'Dark Espresso', 'Natural Oak'],
                'tags' => ['tv unit', 'media console', 'modern'],
                'is_best_seller' => true,
                'avg_rating' => 4.5,
                'review_count' => 63,
                'views' => 720,
                'specifications' => [
                    'TV Size Compatibility' => 'Up to 75 inch',
                    'Storage' => '4 compartments + 2 drawers',
                    'Cable Management' => 'Built-in',
                ],
            ],
            [
                'category_slug' => 'living-room-furniture',
                'name' => 'Luxury Recliner Chair',
                'sku' => 'FS-RC-001',
                'short_description' => 'Premium leather recliner with massage function.',
                'description' => 'Indulge in pure relaxation with our Luxury Recliner Chair. Features genuine leather upholstery, 6-point massage system, heating function, and USB charging ports.',
                'price' => 55000,
                'sale_price' => 48000,
                'stock' => 8,
                'material' => 'Genuine Leather, Steel Frame',
                'dimensions' => '85cm x 90cm x 105cm',
                'weight' => '38kg',
                'colors' => ['Cognac Brown', 'Black', 'Ivory White'],
                'tags' => ['recliner', 'leather', 'massage', 'luxury'],
                'is_featured' => true,
                'avg_rating' => 4.9,
                'review_count' => 156,
                'views' => 1680,
                'specifications' => [
                    'Upholstery' => 'Genuine Leather',
                    'Reclining Angle' => '135 degrees',
                    'Massage Points' => '6',
                    'USB Ports' => '2',
                    'Heating' => 'Yes',
                ],
            ],
            [
                'category_slug' => 'living-room-furniture',
                'name' => 'Accent Chair',
                'sku' => 'FS-AC-001',
                'short_description' => 'Elegant velvet accent chair for modern living rooms.',
                'description' => 'Add a touch of luxury to your living space with this elegant velvet accent chair. Features a sturdy gold metal frame and plush velvet upholstery.',
                'price' => 15000,
                'sale_price' => 12500,
                'stock' => 18,
                'material' => 'Velvet, Gold Metal Frame',
                'dimensions' => '70cm x 75cm x 88cm',
                'weight' => '12kg',
                'colors' => ['Emerald Green', 'Dusty Pink', 'Royal Blue', 'Mustard Yellow'],
                'tags' => ['accent chair', 'velvet', 'luxury'],
                'is_new_arrival' => true,
                'avg_rating' => 4.7,
                'review_count' => 45,
                'views' => 534,
                'specifications' => [
                    'Upholstery' => 'Premium Velvet',
                    'Frame' => 'Gold Metal',
                    'Weight Capacity' => '120kg',
                ],
            ],

            // Bedroom
            [
                'category_slug' => 'bedroom-furniture',
                'name' => 'King Size Platform Bed',
                'sku' => 'FS-BED-001',
                'short_description' => 'Elegant king size bed with upholstered headboard.',
                'description' => 'Transform your bedroom with our King Size Platform Bed. Features a tufted fabric headboard, solid wood slat base, and ample under-bed storage space.',
                'price' => 65000,
                'sale_price' => 55000,
                'stock' => 7,
                'material' => 'Solid Wood, Fabric',
                'dimensions' => '210cm x 195cm x 120cm',
                'weight' => '65kg',
                'colors' => ['Charcoal Grey', 'Cream White', 'Navy Blue'],
                'tags' => ['bed', 'king size', 'bedroom', 'luxury'],
                'is_featured' => true,
                'is_best_seller' => true,
                'avg_rating' => 4.8,
                'review_count' => 203,
                'views' => 2100,
                'specifications' => [
                    'Mattress Size' => 'King (180 x 200cm)',
                    'Headboard Height' => '120cm',
                    'Slat Type' => 'Solid Wood',
                    'Storage' => 'Under-bed',
                    'Assembly' => 'Required',
                ],
            ],
            [
                'category_slug' => 'bedroom-furniture',
                'name' => 'Modern Wardrobe',
                'sku' => 'FS-WD-001',
                'short_description' => '6-door sliding wardrobe with mirror panels.',
                'description' => 'Maximize your bedroom storage with our Modern 6-Door Sliding Wardrobe. Features full-length mirror panels, built-in LED lighting, and customizable internal fittings.',
                'price' => 75000,
                'sale_price' => 68000,
                'stock' => 5,
                'material' => 'MDF, Mirror Glass, Aluminum',
                'dimensions' => '240cm x 60cm x 220cm',
                'weight' => '120kg',
                'colors' => ['White Mirror', 'Dark Espresso Mirror'],
                'tags' => ['wardrobe', 'storage', 'sliding', 'mirror'],
                'is_featured' => true,
                'avg_rating' => 4.7,
                'review_count' => 89,
                'views' => 1450,
                'specifications' => [
                    'Doors' => '6 Sliding Doors',
                    'Mirror' => 'Full Length',
                    'Interior' => 'Hanging Rail, Shelves, Drawers',
                    'LED Lighting' => 'Yes',
                ],
            ],
            [
                'category_slug' => 'bedroom-furniture',
                'name' => 'Minimal Bedside Table',
                'sku' => 'FS-BST-001',
                'short_description' => 'Elegant bedside table with drawer and open shelf.',
                'description' => 'Complete your bedroom setup with this elegant minimal bedside table. Features a drawer for small items and an open shelf for books or decoratives.',
                'price' => 8500,
                'sale_price' => 7000,
                'stock' => 35,
                'material' => 'Solid Wood',
                'dimensions' => '45cm x 40cm x 55cm',
                'weight' => '8kg',
                'colors' => ['Natural Oak', 'Walnut Brown', 'White'],
                'tags' => ['bedside table', 'nightstand', 'bedroom'],
                'is_new_arrival' => true,
                'avg_rating' => 4.5,
                'review_count' => 72,
                'views' => 680,
                'specifications' => [
                    'Drawer' => '1',
                    'Open Shelf' => '1',
                    'Material' => 'Solid Wood',
                ],
            ],

            // Dining
            [
                'category_slug' => 'dining-furniture',
                'name' => 'Dining Table Set (6 Seater)',
                'sku' => 'FS-DT-001',
                'short_description' => 'Premium solid wood dining table with 6 upholstered chairs.',
                'description' => 'Elevate your dining experience with our Premium 6-Seater Dining Table Set. Features a solid sheesham wood table with glass insert and 6 fully upholstered dining chairs.',
                'price' => 85000,
                'sale_price' => 72000,
                'stock' => 4,
                'material' => 'Solid Sheesham Wood, Glass',
                'dimensions' => 'Table: 180cm x 90cm x 76cm',
                'weight' => '85kg',
                'colors' => ['Natural Wood with Grey Chairs', 'Walnut with Cream Chairs'],
                'tags' => ['dining table', 'dining set', '6 seater', 'solid wood'],
                'is_featured' => true,
                'is_best_seller' => true,
                'avg_rating' => 4.9,
                'review_count' => 167,
                'views' => 1890,
                'specifications' => [
                    'Seating' => '6 Persons',
                    'Table Material' => 'Solid Sheesham Wood',
                    'Chair Upholstery' => 'Premium Fabric',
                    'Glass Insert' => '8mm Tempered Glass',
                ],
            ],
            [
                'category_slug' => 'dining-furniture',
                'name' => 'Luxury Dining Chair',
                'sku' => 'FS-DC-001',
                'short_description' => 'Ergonomic dining chair with premium fabric.',
                'description' => 'Comfortable and stylish dining chair featuring ergonomic design, premium fabric upholstery, and solid wood legs for lasting durability.',
                'price' => 8000,
                'sale_price' => 6500,
                'stock' => 40,
                'material' => 'Solid Wood, Fabric',
                'dimensions' => '50cm x 55cm x 90cm',
                'weight' => '6kg',
                'colors' => ['Charcoal', 'Beige', 'Olive Green'],
                'tags' => ['dining chair', 'fabric', 'wood'],
                'avg_rating' => 4.4,
                'review_count' => 93,
                'views' => 780,
                'specifications' => [
                    'Seat Height' => '47cm',
                    'Weight Capacity' => '120kg',
                    'Upholstery' => 'Premium Woven Fabric',
                ],
            ],

            // Office
            [
                'category_slug' => 'office-furniture',
                'name' => 'Ergonomic Office Chair',
                'sku' => 'FS-OC-001',
                'short_description' => 'Premium ergonomic office chair with lumbar support.',
                'description' => 'Boost productivity and comfort with our Premium Ergonomic Office Chair. Features adjustable lumbar support, breathable mesh back, headrest, and 4D armrests.',
                'price' => 28000,
                'sale_price' => 22000,
                'stock' => 22,
                'material' => 'Mesh, Nylon, Chrome',
                'dimensions' => '68cm x 68cm x 110-120cm',
                'weight' => '18kg',
                'colors' => ['Black', 'Grey', 'Blue'],
                'tags' => ['office chair', 'ergonomic', 'mesh', 'adjustable'],
                'is_featured' => true,
                'is_best_seller' => true,
                'avg_rating' => 4.7,
                'review_count' => 215,
                'views' => 2340,
                'specifications' => [
                    'Seat Adjustment' => 'Pneumatic Height Adjustment',
                    'Armrests' => '4D Adjustable',
                    'Lumbar Support' => 'Adjustable',
                    'Headrest' => 'Adjustable',
                    'Base' => 'Chrome 5-Star Base',
                ],
            ],
            [
                'category_slug' => 'office-furniture',
                'name' => 'Executive Study Desk',
                'sku' => 'FS-SD-001',
                'short_description' => 'Premium executive desk with cable management.',
                'description' => 'Create a productive workspace with our Executive Study Desk. Features a spacious work surface, integrated cable management, and a side pedestal with drawers.',
                'price' => 35000,
                'sale_price' => 29000,
                'stock' => 10,
                'material' => 'MDF, Solid Wood Edge',
                'dimensions' => '160cm x 75cm x 76cm',
                'weight' => '42kg',
                'colors' => ['Dark Walnut', 'Light Oak', 'White'],
                'tags' => ['study desk', 'office desk', 'executive'],
                'is_new_arrival' => true,
                'avg_rating' => 4.6,
                'review_count' => 58,
                'views' => 890,
                'specifications' => [
                    'Work Surface' => '160 x 75cm',
                    'Cable Management' => 'Built-in',
                    'Drawers' => '3 (1 lockable)',
                    'CPU Cabinet' => 'Included',
                ],
            ],
            [
                'category_slug' => 'office-furniture',
                'name' => 'Custom Office Desk',
                'sku' => 'FS-COD-001',
                'short_description' => 'L-shaped corner desk for productive workspaces.',
                'description' => 'Maximize your workspace with our L-Shaped Corner Desk. Perfect for dual monitor setup, featuring a clean modern design and ample storage.',
                'price' => 42000,
                'sale_price' => null,
                'stock' => 6,
                'material' => 'Solid Wood, Metal',
                'dimensions' => '200cm x 160cm x 75cm',
                'weight' => '55kg',
                'colors' => ['Black & Wood', 'All White', 'Natural Oak'],
                'tags' => ['L-shaped desk', 'corner desk', 'office'],
                'is_featured' => true,
                'avg_rating' => 4.8,
                'review_count' => 41,
                'views' => 670,
                'specifications' => [
                    'Shape' => 'L-Shaped Corner',
                    'Monitor Support' => 'Dual Monitor Ready',
                    'Material' => 'Solid Wood + Metal',
                ],
            ],

            // Storage
            [
                'category_slug' => 'storage-cabinets',
                'name' => 'Bookshelf Cabinet',
                'sku' => 'FS-BS-001',
                'short_description' => '5-tier open bookshelf with industrial metal frame.',
                'description' => 'Stylish 5-tier bookshelf with an industrial metal frame and solid wood shelves. Perfect for books, decor items, and organizing your space.',
                'price' => 16000,
                'sale_price' => 13500,
                'stock' => 25,
                'material' => 'Solid Wood, Metal',
                'dimensions' => '90cm x 35cm x 180cm',
                'weight' => '20kg',
                'colors' => ['Black Metal + Walnut', 'White Metal + Oak'],
                'tags' => ['bookshelf', 'storage', 'industrial', 'open shelf'],
                'is_best_seller' => true,
                'avg_rating' => 4.6,
                'review_count' => 134,
                'views' => 1120,
                'specifications' => [
                    'Tiers' => '5',
                    'Shelf Material' => 'Solid Wood',
                    'Frame' => 'Heavy Duty Metal',
                    'Weight per shelf' => '30kg',
                ],
            ],
            [
                'category_slug' => 'storage-cabinets',
                'name' => 'Shoe Rack Cabinet',
                'sku' => 'FS-SR-001',
                'short_description' => 'Elegant shoe cabinet with soft-close doors.',
                'description' => 'Keep your entryway organized with our elegant shoe cabinet. Features soft-close doors, multiple shoe racks, and a clean modern design.',
                'price' => 12000,
                'sale_price' => 9500,
                'stock' => 18,
                'material' => 'MDF, Wood',
                'dimensions' => '90cm x 35cm x 110cm',
                'weight' => '22kg',
                'colors' => ['White', 'Walnut Brown', 'Dark Grey'],
                'tags' => ['shoe cabinet', 'storage', 'entryway'],
                'avg_rating' => 4.4,
                'review_count' => 67,
                'views' => 580,
                'specifications' => [
                    'Shoe Capacity' => '12-16 pairs',
                    'Doors' => 'Soft-Close',
                    'Sections' => '3',
                ],
            ],
            [
                'category_slug' => 'storage-cabinets',
                'name' => 'Wall Shelf Set',
                'sku' => 'FS-WS-001',
                'short_description' => 'Set of 3 floating wall shelves.',
                'description' => 'Transform any wall into beautiful display space with our set of 3 floating wall shelves. Easy to install and strong enough for books and decor items.',
                'price' => 6500,
                'sale_price' => 5200,
                'stock' => 45,
                'material' => 'Solid Wood',
                'dimensions' => '60cm x 20cm x 4cm each',
                'weight' => '4kg per set',
                'colors' => ['Natural Wood', 'White', 'Black'],
                'tags' => ['wall shelf', 'floating shelf', 'storage', 'display'],
                'is_new_arrival' => true,
                'avg_rating' => 4.5,
                'review_count' => 89,
                'views' => 750,
                'specifications' => [
                    'Pieces in Set' => '3',
                    'Weight Capacity' => '15kg each',
                    'Material' => 'Solid Pine Wood',
                ],
            ],
            [
                'category_slug' => 'storage-cabinets',
                'name' => 'Console Table',
                'sku' => 'FS-CON-001',
                'short_description' => 'Slim hallway console table with drawer.',
                'description' => 'Elegant slim console table perfect for hallways, entryways, or living rooms. Features a drawer and a lower shelf for extra storage.',
                'price' => 14000,
                'sale_price' => null,
                'stock' => 14,
                'material' => 'Solid Wood, Metal',
                'dimensions' => '110cm x 35cm x 80cm',
                'weight' => '16kg',
                'colors' => ['Gold Metal + Marble Top', 'Black Metal + Wood Top'],
                'tags' => ['console table', 'hallway table', 'slim'],
                'avg_rating' => 4.7,
                'review_count' => 52,
                'views' => 620,
                'specifications' => [
                    'Drawer' => '1',
                    'Lower Shelf' => '1',
                    'Frame' => 'Metal',
                    'Top Material' => 'Marble / Wood',
                ],
            ],

            // Home Decor
            [
                'category_slug' => 'home-decor',
                'name' => 'Decorative Wall Mirror',
                'sku' => 'FS-MR-001',
                'short_description' => 'Premium arched full-length decorative mirror.',
                'description' => 'Add elegance and depth to any room with our Premium Arched Full-Length Mirror. Features a premium gold frame and anti-shatter glass.',
                'price' => 18000,
                'sale_price' => 15000,
                'stock' => 12,
                'material' => 'Metal Frame, Mirror Glass',
                'dimensions' => '80cm x 180cm',
                'weight' => '15kg',
                'colors' => ['Gold', 'Black', 'Silver'],
                'tags' => ['mirror', 'decor', 'wall mirror', 'gold'],
                'is_new_arrival' => true,
                'is_best_seller' => true,
                'avg_rating' => 4.8,
                'review_count' => 112,
                'views' => 1430,
                'specifications' => [
                    'Frame Material' => 'Premium Metal',
                    'Mirror Type' => 'Anti-Shatter',
                    'Shape' => 'Arch',
                    'Mounting' => 'Wall/Floor',
                ],
            ],
            [
                'category_slug' => 'home-decor',
                'name' => 'Modern Floor Lamp',
                'sku' => 'FS-FL-001',
                'short_description' => 'Elegant arc floor lamp with fabric shade.',
                'description' => 'Illuminate your living space with our Modern Arc Floor Lamp. Features a sleek marble base, adjustable arm, and a premium fabric shade that creates warm ambient lighting.',
                'price' => 12000,
                'sale_price' => 9800,
                'stock' => 20,
                'material' => 'Marble, Metal, Fabric',
                'dimensions' => '40cm x 40cm x 175cm',
                'weight' => '8kg',
                'colors' => ['White Marble + Gold', 'Black Marble + Black'],
                'tags' => ['floor lamp', 'lighting', 'arc lamp', 'marble'],
                'is_featured' => true,
                'avg_rating' => 4.6,
                'review_count' => 78,
                'views' => 890,
                'specifications' => [
                    'Base' => 'Natural Marble',
                    'Shade' => 'Linen Fabric',
                    'Bulb' => 'E27, Max 40W',
                    'Adjustable' => 'Yes',
                ],
            ],
            [
                'category_slug' => 'home-decor',
                'name' => 'Wooden Side Table',
                'sku' => 'FS-WST-001',
                'short_description' => 'Solid wood round side table with hairpin legs.',
                'description' => 'Add functional style to any corner with our Solid Wood Round Side Table. Features a natural wood top and elegant hairpin metal legs.',
                'price' => 7500,
                'sale_price' => 6000,
                'stock' => 30,
                'material' => 'Solid Wood, Metal',
                'dimensions' => '50cm diameter x 55cm height',
                'weight' => '5kg',
                'colors' => ['Natural Wood + Black Legs', 'Walnut + Gold Legs'],
                'tags' => ['side table', 'end table', 'round', 'hairpin'],
                'is_new_arrival' => true,
                'avg_rating' => 4.5,
                'review_count' => 56,
                'views' => 640,
                'specifications' => [
                    'Shape' => 'Round',
                    'Top Material' => 'Solid Wood',
                    'Legs' => 'Metal Hairpin',
                ],
            ],
        ];

        foreach ($products as $productData) {
            $categorySlug = $productData['category_slug'];
            unset($productData['category_slug']);

            if (!isset($categories[$categorySlug])) continue;

            $productData['category_id'] = $categories[$categorySlug]->id;
            $productData['slug'] = Str::slug($productData['name']) . '-' . rand(100, 999);

            Product::create($productData);
        }
    }
}
